export type SubjectArea =
  | 'history' | 'math' | 'physics' | 'biology'
  | 'chemistry' | 'literature' | 'geography' | 'civics' | 'general'

export type GradeCategory = 'lower' | 'middle' | 'upper'

export interface LessonPlan {
  uvod: string
  aktivizace: string
  hlavniCast: string
  shrnuti: string
}

export interface QuizItem {
  question: string
  answer: string
}

export interface KlicovyPojem {
  term: string
  definition: string
}

export interface Diferenciace {
  nadany: string
  potrebujeOporu: string
}

/** Student-facing worksheet — printable, activity-based */
export interface PracovniList {
  nadpis: string        // e.g. "Pracovní list: Pythagorova věta"
  instrukce: string     // Instructions shown to the student
  obsah: string         // Activity text — fill-in-blanks / matching / questions
  klicOdpovedi: string  // Teacher's answer key (hidden by default in UI)
}

// ── Student Smart Notes ───────────────────────────────────────────────────────

export type StudyLevel = 'ZŠ' | 'SŠ' | 'VŠ'

export type ExamGoal =
  | 'bezna-pisemka'       // Regular classroom test — no special framing
  | 'prijimaci-zkousky'   // Czech high-school entrance exams (CERMAT)
  | 'maturita'            // Czech graduation exam / didactic test
  | 'statni-zaverecne'    // University state finals / thesis defense level

// ── Two-Speaker Podcast ───────────────────────────────────────────────────────

export type PodcastSpeaker = 'teacher' | 'student'

export interface PodcastTurn {
  /** 'teacher' = female expert, 'student' = male learner (Feynman paraphraser) */
  speaker: PodcastSpeaker
  /** The spoken text for this turn — one natural speech segment */
  text: string
}

/** Legacy — retained for old records already in the database */
export interface AcademicTopic {
  title: string
  deep_explanation: string
  key_authors: string
}

// ── Phase 1: Astra Deep Structure ─────────────────────────────────────────────

/** A self-contained learning module: concept + explanation + analogy */
export interface StudyModule {
  /** Short, clear module title */
  title: string
  /** 4–6 sentence explanation — concrete facts, no filler */
  explanation: string
  /** Real-world analogy that makes the concept click instantly */
  analogy: string
}

/** One multiple-choice question with four options */
export interface QuizQuestion {
  question: string
  /** Exactly 4 options */
  options: [string, string, string, string]
  /** Index of the correct option (0–3) */
  correct_index: 0 | 1 | 2 | 3
  /** Why the correct answer is right — and why the others are wrong */
  explanation_why_correct: string
}

// ── Interactive Game (Phase 11) ───────────────────────────────────────────────

export type GameType = 'sorting' | 'matching'

export interface SortingItem      { id: number; text: string }
export interface GameMatchingPair { left: string; right: string }

export interface InteractiveGame {
  game_type:    GameType
  title:        string
  instructions: string
  /** SortingItem[] when game_type==='sorting', GameMatchingPair[] when 'matching' */
  items: SortingItem[] | GameMatchingPair[]
}

// ── Flashcard (Phase 10.5) ────────────────────────────────────────────────────

export interface Flashcard {
  term: string
  definition: string
}

export interface SmartNotes {
  /** Hook that sparks curiosity before the student dives in */
  introduction: string
  /** 2-sentence absolute core summary — readable in 10 seconds */
  tl_dr: string
  /** 3–4 structured learning modules (replaces core_facts / core_topics) */
  deep_modules: StudyModule[]
  /** 2–3 specific pitfalls teachers / committees love to test */
  exam_traps: string[]
  /** Concrete mnemonic — acronym, absurd story, or visual analogy */
  memory_hack: string
  /** 5 multiple-choice questions for self-testing */
  interactive_quiz: QuizQuestion[]
  /**
   * Single-speaker podcast monologue — generated by the topic route (/api/generate-notes).
   * Sent to /api/tts on demand.
   */
  audio_script?: string

  /**
   * Two-speaker educational dialogue — generated by the BYON route (/api/generate-from-notes).
   * 'teacher' = female expert (nova/shimmer voice).
   * 'student' = male learner applying the Feynman technique (onyx/alloy voice).
   * Each element is one spoken turn; turns are played sequentially by the audio player.
   */
  podcast_script?: PodcastTurn[]

  /** 10 key term/definition flashcards for self-testing */
  flashcards?: Flashcard[]
  /** Interactive mini-game generated alongside the notes */
  interactive_game?: InteractiveGame
  /** Mermaid.js graph TD syntax for a visual mind map */
  mind_map_mermaid?: string

  /** Legacy fields — present in old database records, rendered as fallback */
  core_facts?: string[]
  core_topics?: AcademicTopic[]
}

// ── Essay Grader (Phase 10) ───────────────────────────────────────────────────

export interface GrammarIssue {
  original:    string
  corrected:   string
  explanation: string
}

export interface EssayGrade {
  grade:            string        // 'A', 'B+', 'C', '1', '2', etc.
  percentage:       number        // 0–100
  feedback:         string        // 3–4 paragraphs of constructive narrative
  strengths:        string[]      // 2–3 specific strengths
  improvements:     string[]      // 2–3 specific areas to improve
  grammar_issues:   GrammarIssue[]
  improved_version: string
}

// ── Worksheet 2.0 (Phase 8) ───────────────────────────────────────────────────

export interface MatchingPair {
  term: string
  match: string
}

export interface WorksheetDraft {
  title: string
  /** 6–8 term/definition pairs for matching exercise */
  matching_exercise: MatchingPair[]
  /** 3 deep open-ended questions */
  open_questions: string[]
  /** One synthesis/creative task */
  creative_task: string
  /** Raw SVG markup — textbook-style line-art diagram */
  svg_illustration: string
}

// ── E-U-R Framework (Phase 7.5 Teacher Arsenal) ──────────────────────────────

export interface EURFramework {
  /** Evokace — activate prior knowledge and spark curiosity */
  evocation: string
  /** Uvědomění si informací — core content delivery */
  realization_of_meaning: string
  /** Reflexe — consolidation, exit ticket, transfer */
  reflection: string
}

// ── Phase 7: Research Lab ─────────────────────────────────────────────────────

export interface ResearchTheme {
  theme: string
  description: string
}

export interface ResearchQuote {
  quote: string
  theme: string
}

export interface ResearchAnalysis {
  core_themes: ResearchTheme[]
  key_quotes:  ResearchQuote[]
  synthesis:   string
}

export interface GenerationResult {
  subject: SubjectArea
  subjectLabel: string
  gradeCategory: GradeCategory
  quiz: QuizItem[]
  aiGenerated: boolean

  /** 3 measurable learning objectives */
  cigleHodiny?: string[]
  /** 5 expert-defined key terms */
  klicovePojmy?: KlicovyPojem[]

  // ── Arsenal (new format — returned by updated API) ──
  eur_framework?: EURFramework
  /** Structured worksheet with SVG illustration — Phase 8 format */
  worksheet_draft?: WorksheetDraft
  /** 10-minute group game / dynamic activity */
  group_activity?: string
  /** SVP inclusion tips (ADHD, Dyslexia, etc.) */
  sen_inclusion?: string
  /** Interactive mini-game for the lesson */
  interactive_game?: InteractiveGame
  /** Mermaid.js graph TD syntax for a visual mind map */
  mind_map_mermaid?: string

  // ── Legacy (present in old DB records) ──
  lessonPlan?: LessonPlan
  diferenciace?: Diferenciace
  pracovniList?: PracovniList

  imageUrl?: string | null
}
